---
- name: Import Microsoft's signing key.
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
    state: present
  become: yes

- name: Add VS Code repository.
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Install VS Code.
  dnf:
    name: "{{ vscode_package }}"
    state: present
    update_cache: yes
  become: yes
