---
- name: Import Microsoft's signing key.
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Add VS Code repository.
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present
  become: yes

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install VS Code.
  apt:
    name: "{{ vscode_package }}"
    state: present
  become: yes
