---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Install GPG.
      apt:
        name: [gpg, gpg-agent]
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - { role: ihmels.vscode }
