---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install GnuPG
      ansible.builtin.apt:
        name: [gnupg, gnupg-agent]
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - role: ihmels.vscode
