---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-docker.io/geerlingguy/docker-fedora32-ansible:latest}"
    pre_build_image: true
provisioner:
  name: ansible
